language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
jdk:
  - openjdk7

script: "./build-support/python/clean.sh && ./pants goal clean-all test tests/{java,scala}/com/twitter/common:: && ./pants tests/python/twitter/common:all --no-ng-daemons -vx && ./pants tests/python/twitter/pants:all"

notifications:
  email:
      - john.sirois@gmail.com

